# Schritt 5: Einsatz eines Datenanalysten
Um mithilfe von Python und Pandas Erkenntnisse aus den Tabellen zu gewinnen, wird ein
Datenanalyst eingestellt. Fahre mit den folgenden Aufgaben fort:
• Rufe Daten aus der Datenbank ab und erstelle einen Pandas-Dataframe

In [1]:
import pandas as pd
from sqlalchemy import create_engine

#### Mit dem SQL Server verbinden

In [9]:
engine= create_engine("postgresql+psycopg2://postgres:postgres@localhost:5432/MegaStore365")
with engine.connect() as connection:
    print("Verbunden")

Verbunden

#### Testabfrage mit Pandas

In [13]:
df = pd.read_sql('SELECT * FROM "Kunden" Limit 5;', engine)
print(df)

   KundenID          KundeName  \
0         1         Alla Mawne
1         2    Barret Aaronson
2         3    Bobbee McClaren
3         4  Celeste Lidington
4         5        Dario Pavis

                                        KundeAdresse  KundeKreditkarte
0      Kavalierhaus am Schlosspark, 16831 Rheinsberg  5314574774112590
1  Habsburgerstrasse 133, 79104 Freiburg im Breisgau  5410033003668250
2                Potsdamer Strasse 46, 14469 Potsdam  5270254082243370
3                         Am Eckey 3, 58239 Schwerte  5514830264595360
4                  Michaelisstrasse 44, 99084 Erfurt  5282418605703000

#### • Welcher Kunde hat am meisten bezahlt? Und wie viel hat er bezahlt?

In [22]:
# Top Kunde
TopKunde = """
SELECT
    k."KundenID",
    k."KundeName",
    SUM(v."Menge" * p."ProduktPreis") AS "Gesamtbetrag"
FROM
"Verkaeufe" v
JOIN "Kunden" k USING ("KundenID")
JOIN "Produkte" p USING ("ProduktID")
GROUP BY
k."KundenID", k."KundeName"
ORDER BY
    "Gesamtbetrag" DESC
LIMIT 1;
"""

In [33]:
top_kunde_df = pd.read_sql(TopKunde, engine)

top_kunde_df

   KundenID       KundeName  Gesamtbetrag
0        19  Linnet Firmage      121378.0

#### • Über welchen Zeitraum belaufen sich die Daten der Bestellungen?

In [34]:
Bestelldatum = """
SELECT
    MIN("Bestelldatum") AS "Erste_Bestellung",
    MAX("Bestelldatum") AS "Letzte_Bestellung"
FROM "Verkaeufe"
"""

In [35]:
Bestelldatum_df =  pd.read_sql(Bestelldatum, engine)

Bestelldatum_df

  Erste_Bestellung Letzte_Bestellung
0       2020-10-21        2023-06-04

#### • An welchem Wochentag wird am häufigsten eingekauft?

In [36]:
TopVerkaufstag = """
SELECT
    TO_CHAR("Bestelldatum", 'Day') AS "Wochentag",
    COUNT(*) AS "Anzahl_Bestellungen"
FROM 
    "Verkaeufe"
GROUP BY 
    "Wochentag"
ORDER BY 
    "Anzahl_Bestellungen" DESC
LIMIT 1;
"""

In [37]:
TopVerkaufstag_df= pd.read_sql(TopVerkaufstag, engine)

TopVerkaufstag_df

   Wochentag  Anzahl_Bestellungen
0  Wednesday                   21